# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\mixaj\Documents\Python1_2021\Quiz app\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Quiz")
        MainWindow.resize(1000, 800)
        MainWindow.setStyleSheet("background: #CD95FF;")
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.pushButton = QtWidgets.QPushButton(MainWindow)
        self.pushButton.setGeometry(QtCore.QRect(300,300,200,150))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setText("push")

        '''self.image = QtGui.QPixmap("./logo.png")
        self.lable = QtWidgets.QLabel(MainWindow)
        self.lable.setPixmap(self.image)

        self.gridLayoutWidget = QtWidgets.QGridLayout(MainWindow)
        self.gridLayoutWidget.addWidget(self.lable,1,1)
        self.setLayout(self.gridLayoutWidget)'''



        #self.gridLayoutWidget = QtWidgets.QWidget(MainWindow)
        #self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        

        self.gridLayout = QtWidgets.QGridLayout(MainWindow)
        #self.gridLayout.setGeometry(QtCore.QRect(0,0,800,140))
        self.gridLayout.setObjectName("gridLayout")

        self.image = QtGui.QPixmap("welcome.png")
        self.logo = QtWidgets.QLabel(MainWindow)
        self.logo.setPixmap(self.image)
        

        self.gridLayout.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.gridLayout.addWidget(self.logo,0,0)
        #self.gridLayout.setGeometry(QtCore.QRect(0,0,800,200))
        
        #MainWindow.setPushButton(self.pushButton)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    #def frame1(self,MainWindow):


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Quiz", "Quiz"))
        
